
KINESIS_DEFAULT_RECORDS_PER_REQUEST = 100
KINESIS_DEFAULT_STREAM_NAME = 'DriverLocationStream'
KINESIS_DEFAULT_DELAY = 0.3

PRODUCER_DEFAULT_MAX_THREADS = 10
PRODUCER_DEFAULT_BUFFER_SIZE = 2000

GEO_DEFAULT_DATA_DIR = "./tmp"
GEO_DEFAULT_METERS_PER_PING = 10
GEO_DEFAULT_POINTS_DIR = "points"
GEO_DEFAULT_MAPS_DIR = "maps"
GEO_MAX_MARKERS = 40

